import { Injectable, NotFoundException } from "@nestjs/common";
import { AssignmentStatus, AssignmentStrategy, WorkflowEventType, WorkflowStatus } from "@prisma/client";
import { PrismaService } from "../../../core/prisma/prisma.service";
import { NotificationService } from "../../notifications/services/notification.service";
import { ActivityService } from "../../activity/services/activity.service";

/**
 * WorkflowAutoAssignService
 *
 * After a client is onboarded with selected services, this service:
 * 1. Creates a workflow for the client (subjectType = "CLIENT")
 * 2. Reads each selected service's task templates and generates service-wise tasks.
 * 3. Assigns tasks to the service department using the configured assignment strategy.
 *
 * Future-proofing for multiple owners per service:
 * The Service model currently holds a single `ownerId`. When you have multiple
 * people for the same service (e.g., two Social Media Managers), the recommended
 * approach is:
 *   - Add a `ServiceOwner` join table: serviceId + userId + isActive
 *   - Auto-assign uses round-robin or least-load strategy across active owners
 *   - This service's `resolveOwner()` method below already abstracts that logic
 *     so you only need to update it when the time comes.
 */
@Injectable()
export class WorkflowAutoAssignService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly notificationService: NotificationService,
    private readonly activityService: ActivityService
  ) { }

  async onboardClient(companyId: string, actorId: string, clientId: string, regenerate = false) {
    const client = await this.prisma.client.findFirst({
      where: { id: clientId, companyId },
      include: {
        services: {
          include: {
            service: {
              include: { owner: true },
            },
          },
        },
      },
    });

    if (!client) throw new NotFoundException("Client not found");

    const clientServicesToProcess = client.services;

    if (clientServicesToProcess.length === 0) throw new NotFoundException("Client has no selected services");

    const settings = await this.prisma.workflowSetting.upsert({
      where: { companyId },
      update: {},
      create: { companyId },
    });

    const workflow = await this.prisma.workflow.upsert({
      where: {
        companyId_subjectType_subjectId: {
          companyId,
          subjectType: "CLIENT",
          subjectId: clientId,
        },
      },
      update: {
        title: `Client Onboarding - ${client.name}`,
        isAutoGenerated: true,
        metadata: this.workflowMetadata(client, clientServicesToProcess, settings.assignmentStrategy),
        version: { increment: 1 },
      },
      create: {
        companyId,
        subjectType: "CLIENT",
        subjectId: clientId,
        title: `Client Onboarding - ${client.name}`,
        createdById: actorId,
        isAutoGenerated: true,
        startedAt: new Date(),
        metadata: this.workflowMetadata(client, clientServicesToProcess, settings.assignmentStrategy),
      },
    });

    if (regenerate) {
      await this.prisma.task.deleteMany({ where: { workflowId: workflow.id, companyId, isCustom: false } });
      await this.prisma.workflowAssignment.updateMany({
        where: { workflowId: workflow.id, companyId, status: { in: [AssignmentStatus.ASSIGNED, AssignmentStatus.ACCEPTED] } },
        data: { status: AssignmentStatus.TRANSFERRED, closedAt: new Date() },
      });
    } else {
      const existingGeneratedTasks = await this.prisma.task.count({ where: { workflowId: workflow.id, companyId, isCustom: false } });
      if (existingGeneratedTasks > 0) return workflow;
    }

    await this.prisma.workflowHistory.create({
      data: {
        workflowId: workflow.id,
        companyId,
        actorId,
        eventType: regenerate ? WorkflowEventType.OVERRIDDEN : WorkflowEventType.CREATED,
        toStatus: WorkflowStatus.PENDING,
        remarks: regenerate ? "Workflow regenerated from current service templates" : "Workflow created automatically after client onboarding",
        metadata: this.workflowMetadata(client, clientServicesToProcess, settings.assignmentStrategy),
      },
    });

    let createdTasks = 0;
    let firstDepartmentId: string | null = null;
    const departmentAssignments = new Map<string, string>();

    const allDepartments = await this.prisma.department.findMany({ where: { companyId, isActive: true } });
    const getDepartmentId = (requestedName: string) => {
      if (!requestedName) return null;
      const target = requestedName.toLowerCase().replace(/[^a-z0-9]/g, "");
      const match = allDepartments.find((d) => {
        const nameLower = d.name.toLowerCase().replace(/[^a-z0-9]/g, "");
        const codeLower = d.code.toLowerCase().replace(/[^a-z0-9]/g, "");

        const isGraphicTarget = target.includes("graphic") || target.includes("grapic") || target.includes("design");
        const isGraphicDept = nameLower.includes("graphic") || nameLower.includes("grapic") || nameLower.includes("design") || codeLower.includes("graphic") || codeLower.includes("grapic") || codeLower.includes("design");

        const isSocialTarget = target.includes("social") || target.includes("smm");
        const isSocialDept = nameLower.includes("social") || nameLower.includes("smm") || codeLower.includes("social") || codeLower.includes("smm");

        const isVideoTarget = target.includes("video") || target.includes("reel") || target.includes("edit");
        const isVideoDept = nameLower.includes("video") || nameLower.includes("reel") || nameLower.includes("edit") || codeLower.includes("video") || codeLower.includes("reel") || codeLower.includes("edit");

        return (
          nameLower === target ||
          codeLower === target ||
          (isGraphicTarget && isGraphicDept) ||
          (isSocialTarget && isSocialDept) ||
          (isVideoTarget && isVideoDept)
        );
      });
      return match ? match.id : null;
    };

    const createdTasksByTitle = new Map<string, string>();

    for (const clientService of clientServicesToProcess) {
      const service = clientService.service;
      const config = clientService.configuration as any;

      const dynamicTasks = this.resolveDynamicTasks(service, config, clientServicesToProcess);

      for (const [index, taskDef] of dynamicTasks.entries()) {
        const taskDepartmentId = taskDef.departmentName
          ? (getDepartmentId(taskDef.departmentName) ?? service.departmentId ?? getDepartmentId(service.name))
          : (service.departmentId ?? getDepartmentId(service.name));

        if (!firstDepartmentId && taskDepartmentId) firstDepartmentId = taskDepartmentId;

        const ownerId = await this.resolveDepartmentOwner(companyId, taskDepartmentId, settings.assignmentStrategy, service.ownerId);

        if (taskDepartmentId && ownerId && !departmentAssignments.has(taskDepartmentId)) {
          departmentAssignments.set(taskDepartmentId, ownerId);
        }

        const dependsOnTaskId = taskDef.dependsOnTitle ? createdTasksByTitle.get(taskDef.dependsOnTitle) ?? null : null;

        const task = await this.prisma.task.create({
          data: {
            companyId,
            workflowId: workflow.id,
            createdById: actorId,
            type: taskDef.type,
            serviceId: service.id,
            serviceName: service.name,
            departmentId: taskDepartmentId,
            templateKey: `${service.id}:${index}`,
            title: taskDef.title,
            dependsOnTaskId,
            isLocked: taskDef.isLocked ?? false,
            status: ownerId ? WorkflowStatus.ASSIGNED : WorkflowStatus.PENDING,
            assignedToId: ownerId ?? undefined,
          },
        });
        createdTasks += 1;
        createdTasksByTitle.set(task.title, task.id);

        if (ownerId) {
          await this.notificationService.notify(
            companyId,
            ownerId,
            "New Task Auto-Assigned",
            `You have been auto-assigned '${task.title}' for client '${client.name}'`
          );
        }
      }
    }

    for (const [departmentId, assignedToId] of departmentAssignments.entries()) {
      await this.prisma.workflowAssignment.create({
        data: { workflowId: workflow.id, companyId, departmentId, assignedById: actorId, assignedToId, remarks: "Auto-assigned by workflow automation" },
      });
      await this.prisma.workflowHistory.create({
        data: { workflowId: workflow.id, companyId, actorId, eventType: WorkflowEventType.ASSIGNED, toStatus: WorkflowStatus.ASSIGNED, toUserId: assignedToId, departmentId, remarks: "Department tasks auto-assigned" },
      });
    }

    await this.prisma.workflow.update({
      where: { id: workflow.id },
      data: {
        status: departmentAssignments.size > 0 ? WorkflowStatus.ASSIGNED : WorkflowStatus.PENDING,
        currentDepartmentId: firstDepartmentId,
      },
    });

    await this.prisma.workflowHistory.create({
      data: {
        workflowId: workflow.id,
        companyId,
        actorId,
        eventType: WorkflowEventType.TASKS_GENERATED,
        toStatus: departmentAssignments.size > 0 ? WorkflowStatus.ASSIGNED : WorkflowStatus.PENDING,
        remarks: `${createdTasks} service tasks generated automatically`,
        metadata: { taskCount: createdTasks, serviceCount: clientServicesToProcess.length },
      },
    });

    await this.activityService.log(
      companyId,
      actorId,
      "client_onboarded",
      `Client '${client.name}' onboarded. Workflow and ${createdTasks} task(s) created.`
    );

    const refreshedWorkflow = await this.prisma.workflow.findFirst({ where: { id: workflow.id, companyId } });
    if (!refreshedWorkflow) throw new NotFoundException("Workflow not found after automation");
    return refreshedWorkflow;
  }

  private async resolveDepartmentOwner(companyId: string, departmentId: string | null, strategy: AssignmentStrategy, fallbackOwnerId: string | null): Promise<string | null> {
    if (strategy === AssignmentStrategy.MANUAL_OVERRIDE) return fallbackOwnerId;

    const department = departmentId
      ? await this.prisma.department.findFirst({ where: { id: departmentId, companyId, isActive: true } })
      : null;

    let departmentUsers: any[] = [];
    const allCompanyUsers = await this.prisma.user.findMany({
      where: { companyId, status: "ACTIVE" },
      orderBy: { createdAt: "asc" },
    });

    if (department) {
      const deptNameLower = department.name.toLowerCase().replace(/[^a-z0-9]/g, "");
      const deptCodeLower = department.code.toLowerCase().replace(/[^a-z0-9]/g, "");

      departmentUsers = allCompanyUsers.filter((u) => {
        const uDept = (u.department || "").toLowerCase().replace(/[^a-z0-9]/g, "");
        const uDesig = (u.designation || "").toLowerCase().replace(/[^a-z0-9]/g, "");

        const isGraphicDept = deptNameLower.includes("graphic") || deptNameLower.includes("grapic") || deptNameLower.includes("design");
        const isGraphicUser = uDept.includes("graphic") || uDept.includes("grapic") || uDept.includes("design") || uDesig.includes("graphic") || uDesig.includes("grapic") || uDesig.includes("design");

        const isSocialDept = deptNameLower.includes("social") || deptNameLower.includes("smm");
        const isSocialUser = uDept.includes("social") || uDept.includes("smm") || uDesig.includes("social") || uDesig.includes("smm");

        const isVideoDept = deptNameLower.includes("video") || deptNameLower.includes("reel") || deptNameLower.includes("edit");
        const isVideoUser = uDept.includes("video") || uDept.includes("reel") || uDept.includes("edit") || uDesig.includes("video") || uDesig.includes("reel") || uDesig.includes("edit");

        return (
          u.departmentId === department.id ||
          uDept === deptNameLower ||
          uDept === deptCodeLower ||
          uDept.includes(deptNameLower) ||
          (isGraphicDept && isGraphicUser) ||
          (isSocialDept && isSocialUser) ||
          (isVideoDept && isVideoUser)
        );
      });
    }

    if (departmentUsers.length === 0) {
      if (!department && allCompanyUsers.length === 1) return allCompanyUsers[0].id;
      if (!department && fallbackOwnerId) return fallbackOwnerId;
      return null;
    }

    if (departmentUsers.length === 1) return departmentUsers[0].id;

    if (departmentUsers.length > 1 && strategy === AssignmentStrategy.ROUND_ROBIN) {
      const lastTask = await this.prisma.task.findFirst({
        where: { companyId, departmentId, assignedToId: { not: null } },
        orderBy: { createdAt: "desc" },
      });
      const lastIndex = departmentUsers.findIndex((user) => user.id === lastTask?.assignedToId);
      return departmentUsers[(lastIndex + 1) % departmentUsers.length].id;
    }

    if (departmentUsers.length > 1) {
      const loads = await Promise.all(
        departmentUsers.map(async (user) => ({
          user,
          count: await this.prisma.task.count({
            where: { companyId, assignedToId: user.id, status: { in: [WorkflowStatus.PENDING, WorkflowStatus.ASSIGNED, WorkflowStatus.IN_PROGRESS, WorkflowStatus.REVIEW, WorkflowStatus.REVISION] } },
          }),
        }))
      );
      loads.sort((a, b) => a.count - b.count);
      return loads[0].user.id;
    }

    return fallbackOwnerId ?? null;
  }

  private resolveDynamicTasks(service: any, config: any, allServicesConfig?: any[]): { title: string; departmentName?: string; type: any; dependsOnTitle?: string; isLocked?: boolean }[] {
    const serviceName = (service.name || "").toLowerCase().replace(/\s+/g, "");
    const tasks: { title: string; departmentName?: string; type: any; dependsOnTitle?: string; isLocked?: boolean }[] = [];

    if ((serviceName.includes("socialmedia") || serviceName.includes("smm") || serviceName.includes("social")) && config) {
      // 1. Social Media Manager Strategy & Planning Tasks
      tasks.push({ title: "Monthly Strategy", departmentName: "Social Media Manager", type: "CONTENT" });
      tasks.push({ title: "Content Calendar & Planning", departmentName: "Social Media Manager", type: "CONTENT" });

      // 2. 1-by-1 Itemized Handover Chains for Static Posts
      const staticPosts = parseInt(config.staticPosts || "0");
      for (let i = 1; i <= staticPosts; i++) {
        const postTitle = `Design Post ${i}`;
        tasks.push({ title: postTitle, departmentName: "Graphics Designer", type: "GRAPHIC" });
        tasks.push({
          title: `Schedule & Publish Post ${i}`,
          departmentName: "Social Media Manager",
          type: "CONTENT",
          dependsOnTitle: postTitle,
          isLocked: true,
        });
      }

      // 3. 1-by-1 Itemized Handover Chains for Carousel Posts
      const carouselPosts = parseInt(config.carouselPosts || "0");
      for (let i = 1; i <= carouselPosts; i++) {
        const carouselTitle = `Design Carousel ${i}`;
        tasks.push({ title: carouselTitle, departmentName: "Graphics Designer", type: "GRAPHIC" });
        tasks.push({
          title: `Schedule & Publish Carousel ${i}`,
          departmentName: "Social Media Manager",
          type: "CONTENT",
          dependsOnTitle: carouselTitle,
          isLocked: true,
        });
      }

      // 4. 1-by-1 Itemized Handover Chains for Stories
      const stories = parseInt(config.stories || "0");
      for (let i = 1; i <= stories; i++) {
        const storyTitle = `Design Story ${i}`;
        tasks.push({ title: storyTitle, departmentName: "Graphics Designer", type: "GRAPHIC" });
        tasks.push({
          title: `Schedule & Publish Story ${i}`,
          departmentName: "Social Media Manager",
          type: "CONTENT",
          dependsOnTitle: storyTitle,
          isLocked: true,
        });
      }

      // 5. 1-by-1 Itemized Handover Chains for Reels
      const reels = parseInt(config.reels || "0");
      for (let i = 1; i <= reels; i++) {
        const reelTitle = `Edit Reel ${i}`;
        tasks.push({ title: reelTitle, departmentName: "Video Editor", type: "REEL" });
        tasks.push({
          title: `Schedule & Publish Reel ${i}`,
          departmentName: "Social Media Manager",
          type: "CONTENT",
          dependsOnTitle: reelTitle,
          isLocked: true,
        });
      }

      // 6. Account Manager Tasks
      if (config.monthlyReport !== false) {
        tasks.push({ title: "Review & Send Monthly Report", departmentName: "Account Manager", type: "GENERIC" });
      }

      return tasks;
    }

    if ((serviceName.includes("graphic") || serviceName.includes("design")) && config) {
      let posts = parseInt(config.staticPosts || "0");
      let carousels = parseInt(config.carouselPosts || "0");
      let stories = parseInt(config.stories || "0");
      let reelCovers = parseInt(config.reelCovers || "0");

      if (config.importFromSmm && allServicesConfig) {
        const smmConfig = allServicesConfig.find((cs: any) => {
          const sName = (cs.service?.name || "").toLowerCase().replace(/\s+/g, "");
          return sName.includes("socialmedia") || sName.includes("smm") || sName.includes("social");
        })?.configuration as any;

        if (smmConfig) {
          posts = parseInt(smmConfig.staticPosts || "0");
          carousels = parseInt(smmConfig.carouselPosts || "0");
          stories = parseInt(smmConfig.stories || "0");
          reelCovers = parseInt(smmConfig.reels || "0");
        }
      }

      for (let i = 1; i <= posts; i++) tasks.push({ title: `Design Post ${i}`, departmentName: "Graphics Designer", type: "GRAPHIC" });
      for (let i = 1; i <= carousels; i++) tasks.push({ title: `Design Carousel ${i}`, departmentName: "Graphics Designer", type: "GRAPHIC" });
      for (let i = 1; i <= stories; i++) tasks.push({ title: `Design Story ${i}`, departmentName: "Graphics Designer", type: "GRAPHIC" });
      for (let i = 1; i <= reelCovers; i++) tasks.push({ title: `Design Reel Cover ${i}`, departmentName: "Graphics Designer", type: "GRAPHIC" });

      return tasks;
    }

    if ((serviceName.includes("video") || serviceName.includes("reel") || serviceName.includes("edit")) && config) {
      let reels = parseInt(config.reels || "0");
      let reelCovers = parseInt(config.reelCovers || "0");

      for (let i = 1; i <= reels; i++) {
        tasks.push({ title: `Edit Reel ${i}`, departmentName: "Video Editor", type: "REEL" });
      }
      for (let i = 1; i <= reelCovers; i++) {
        tasks.push({ title: `Design Reel Cover ${i}`, departmentName: "Graphics Designer", type: "GRAPHIC" });
      }
      return tasks;
    }

    let resultTasks: { title: string; departmentName?: string; type: any }[] = [];
    if (Array.isArray(service.taskTemplates) && service.taskTemplates.length > 0) {
      resultTasks = service.taskTemplates.map((item: string) => ({ title: item.trim(), type: service.taskType || "GENERIC" })).filter((t: any) => t.title);
    } else {
      if (serviceName.includes("graphic") || serviceName.includes("design")) {
        resultTasks = [
          { title: "Design Post 1", departmentName: "Graphics Designer", type: "GRAPHIC" },
          { title: "Design Post 2", departmentName: "Graphics Designer", type: "GRAPHIC" },
          { title: "Design Story 1", departmentName: "Graphics Designer", type: "GRAPHIC" }
        ];
      } else if (serviceName.includes("social") || serviceName.includes("smm")) {
        resultTasks = [
          { title: "Monthly Strategy", departmentName: "Social Media Manager", type: "CONTENT" },
          { title: "Content Calendar", departmentName: "Social Media Manager", type: "CONTENT" },
          { title: "Caption Planning", departmentName: "Social Media Manager", type: "CONTENT" },
          { title: "Hashtag Research", departmentName: "Social Media Manager", type: "CONTENT" },
          { title: "Scheduling", departmentName: "Social Media Manager", type: "CONTENT" },
          { title: "Publishing", departmentName: "Social Media Manager", type: "CONTENT" },
          { title: "Monthly Report", departmentName: "Social Media Manager", type: "CONTENT" }
        ];
      } else if (serviceName.includes("video") || serviceName.includes("reel") || serviceName.includes("edit")) {
        resultTasks = [
          { title: "Edit Reel 1", departmentName: "Video Editor", type: "REEL" },
          { title: "Edit Reel 2", departmentName: "Video Editor", type: "REEL" }
        ];
      } else {
        resultTasks = [{ title: `${service.name} Deliverables`, type: service.taskType || "GENERIC" }];
      }
    }

    return resultTasks;
  }

  private workflowMetadata(client: any, clientServices: any[], assignmentStrategy: AssignmentStrategy) {
    return {
      autoGenerated: true,
      clientName: client.name,
      assignmentStrategy,
      services: clientServices.map((cs) => ({
        id: cs.service.id,
        name: cs.service.name,
        departmentId: cs.service.departmentId ?? null,
        templateCount: this.resolveDynamicTasks(cs.service, cs.configuration).length,
      })),
    };
  }
}
